"""Initial Elowyn v0.1 World State schema.

Revision ID: 0001_initial
Revises:
Create Date: 2026-08-22
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conversations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "transport",
            sa.Enum(
                "TELEGRAM",
                "INTERNAL",
                name="transport_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("external_conversation_id", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "transport", "external_conversation_id", name="uq_conversation_transport_external"
        ),
    )
    op.create_table(
        "entities",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "entity_type",
            sa.Enum(
                "TASK",
                "PROJECT",
                "GOAL",
                "DECISION",
                name="entity_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("superseded_by_entity_id", sa.Uuid(), nullable=True),
        sa.Column("removed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["superseded_by_entity_id"], ["entities.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_entities_entity_type"), "entities", ["entity_type"], unique=False)
    op.create_table(
        "decisions",
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("chosen_option", sa.Text(), nullable=False),
        sa.Column("reasoning_summary", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "SUPERSEDED",
                "REVOKED",
                name="decision_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("supersedes_decision_id", sa.Uuid(), nullable=True),
        sa.Column(
            "decided_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["entity_id"], ["entities.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["supersedes_decision_id"], ["decisions.entity_id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("entity_id"),
    )
    op.create_index(op.f("ix_decisions_status"), "decisions", ["status"], unique=False)
    op.create_table(
        "messages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column(
            "author",
            sa.Enum(
                "USER",
                "ASSISTANT",
                "SYSTEM",
                "EXTERNAL",
                name="message_author",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("external_message_id", sa.String(length=255), nullable=True),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column(
            "raw_payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("conversation_id", "external_message_id", name="uq_message_external"),
    )
    op.create_index(
        op.f("ix_messages_conversation_id"), "messages", ["conversation_id"], unique=False
    )
    op.create_table(
        "decision_alternatives",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("decision_id", sa.Uuid(), nullable=False),
        sa.Column("option_text", sa.Text(), nullable=False),
        sa.Column("rejection_summary", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["decision_id"], ["decisions.entity_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_decision_alternatives_decision_id"),
        "decision_alternatives",
        ["decision_id"],
        unique=False,
    )
    op.create_table(
        "sources",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum(
                "USER_MESSAGE",
                "ASSISTANT_INFERENCE",
                "SYSTEM",
                "EXTERNAL",
                name="source_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("message_id", sa.Uuid(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("reason_summary", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence IS NULL OR (confidence >= 0 AND confidence <= 1)",
            name="ck_source_confidence",
        ),
        sa.ForeignKeyConstraint(["message_id"], ["messages.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sources_source_type"), "sources", ["source_type"], unique=False)
    op.create_table(
        "entity_relations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_entity_id", sa.Uuid(), nullable=False),
        sa.Column("target_entity_id", sa.Uuid(), nullable=False),
        sa.Column(
            "relation_type",
            sa.Enum(
                "RELATED_TO",
                "AFFECTS",
                "SUPPORTS",
                "CONTRADICTS",
                "DERIVED_FROM",
                name="relation_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence IS NULL OR (confidence >= 0 AND confidence <= 1)",
            name="ck_entity_relation_confidence",
        ),
        sa.CheckConstraint(
            "source_entity_id <> target_entity_id", name="ck_entity_relation_not_self"
        ),
        sa.ForeignKeyConstraint(["source_entity_id"], ["entities.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["target_entity_id"], ["entities.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "source_entity_id", "target_entity_id", "relation_type", name="uq_entity_relation"
        ),
    )
    op.create_index(
        op.f("ix_entity_relations_relation_type"),
        "entity_relations",
        ["relation_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_entity_relations_source_entity_id"),
        "entity_relations",
        ["source_entity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_entity_relations_target_entity_id"),
        "entity_relations",
        ["target_entity_id"],
        unique=False,
    )
    op.create_table(
        "goals",
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "ACHIEVED",
                "PAUSED",
                "ABANDONED",
                name="goal_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("importance", sa.Integer(), nullable=True),
        sa.Column("importance_source_id", sa.Uuid(), nullable=True),
        sa.Column("target_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "target_date_type",
            sa.Enum(
                "SOFT",
                "HARD",
                name="goal_target_date_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column("parent_goal_id", sa.Uuid(), nullable=True),
        sa.Column("achieved_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "importance IS NULL OR (importance >= 1 AND importance <= 5)", name="ck_goal_importance"
        ),
        sa.ForeignKeyConstraint(["entity_id"], ["entities.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["importance_source_id"], ["sources.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["parent_goal_id"], ["goals.entity_id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("entity_id"),
    )
    op.create_index(op.f("ix_goals_parent_goal_id"), "goals", ["parent_goal_id"], unique=False)
    op.create_index(op.f("ix_goals_status"), "goals", ["status"], unique=False)
    op.create_table(
        "operations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "actor_type",
            sa.Enum(
                "USER",
                "ASSISTANT",
                "SYSTEM",
                name="actor_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "projects",
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PLANNED",
                "ACTIVE",
                "PAUSED",
                "COMPLETED",
                "CANCELLED",
                "ARCHIVED",
                name="project_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("importance", sa.Integer(), nullable=True),
        sa.Column("importance_source_id", sa.Uuid(), nullable=True),
        sa.Column("target_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "target_date_type",
            sa.Enum(
                "SOFT",
                "HARD",
                name="project_target_date_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column("parent_project_id", sa.Uuid(), nullable=True),
        sa.Column("current_summary", sa.Text(), nullable=True),
        sa.Column("current_summary_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "importance IS NULL OR (importance >= 1 AND importance <= 5)",
            name="ck_project_importance",
        ),
        sa.ForeignKeyConstraint(["entity_id"], ["entities.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["importance_source_id"], ["sources.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["parent_project_id"], ["projects.entity_id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("entity_id"),
    )
    op.create_index(
        op.f("ix_projects_parent_project_id"), "projects", ["parent_project_id"], unique=False
    )
    op.create_index(op.f("ix_projects_status"), "projects", ["status"], unique=False)
    op.create_table(
        "source_dependencies",
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("evidence_source_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("source_id <> evidence_source_id", name="ck_source_dependency_not_self"),
        sa.ForeignKeyConstraint(["evidence_source_id"], ["sources.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("source_id", "evidence_source_id"),
    )
    op.create_table(
        "events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("operation_id", sa.Uuid(), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "ENTITY_CREATED",
                "ENTITY_UPDATED",
                "ENTITY_SUPERSEDED",
                "TASK_CREATED",
                "TASK_UPDATED",
                "TASK_STATUS_CHANGED",
                "TASK_COMPLETED",
                "TASK_CANCELLED",
                "PROJECT_CREATED",
                "PROJECT_UPDATED",
                "PROJECT_STATUS_CHANGED",
                "PROJECT_COMPLETED",
                "PROJECT_CANCELLED",
                "GOAL_CREATED",
                "GOAL_UPDATED",
                "GOAL_STATUS_CHANGED",
                "GOAL_ACHIEVED",
                "SUCCESS_CRITERION_UPDATED",
                "DECISION_CREATED",
                "DECISION_SUPERSEDED",
                "DECISION_REVOKED",
                "RELATION_CREATED",
                "RELATION_REMOVED",
                "UNDO_APPLIED",
                name="event_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("entity_id", sa.Uuid(), nullable=True),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column("reverses_event_id", sa.Uuid(), nullable=True),
        sa.Column(
            "changes",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["entity_id"], ["entities.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["operation_id"], ["operations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["reverses_event_id"], ["events.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_events_created_at"), "events", ["created_at"], unique=False)
    op.create_index(op.f("ix_events_entity_id"), "events", ["entity_id"], unique=False)
    op.create_index(op.f("ix_events_event_type"), "events", ["event_type"], unique=False)
    op.create_index(op.f("ix_events_operation_id"), "events", ["operation_id"], unique=False)
    op.create_table(
        "project_goal_links",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("goal_id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence IS NULL OR (confidence >= 0 AND confidence <= 1)",
            name="ck_project_goal_confidence",
        ),
        sa.ForeignKeyConstraint(["goal_id"], ["goals.entity_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.entity_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("project_id", "goal_id"),
    )
    op.create_table(
        "success_criteria",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("goal_id", sa.Uuid(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "UNKNOWN",
                "IN_PROGRESS",
                "MET",
                "NOT_MET",
                name="success_criterion_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("evaluation_summary", sa.Text(), nullable=True),
        sa.Column("created_source_id", sa.Uuid(), nullable=True),
        sa.Column("evaluation_source_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence IS NULL OR (confidence >= 0 AND confidence <= 1)",
            name="ck_success_criterion_confidence",
        ),
        sa.ForeignKeyConstraint(["created_source_id"], ["sources.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["evaluation_source_id"], ["sources.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["goal_id"], ["goals.entity_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_success_criteria_goal_id"), "success_criteria", ["goal_id"], unique=False
    )
    op.create_table(
        "tasks",
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "TODO",
                "IN_PROGRESS",
                "BLOCKED",
                "WAITING",
                "DONE",
                "CANCELLED",
                name="task_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("importance", sa.Integer(), nullable=True),
        sa.Column("importance_source_id", sa.Uuid(), nullable=True),
        sa.Column("deadline_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "deadline_type",
            sa.Enum(
                "SOFT", "HARD", name="task_deadline_type", native_enum=False, create_constraint=True
            ),
            nullable=True,
        ),
        sa.Column("estimated_duration_minutes", sa.Integer(), nullable=True),
        sa.Column("estimate_source_id", sa.Uuid(), nullable=True),
        sa.Column("parent_task_id", sa.Uuid(), nullable=True),
        sa.Column("primary_project_id", sa.Uuid(), nullable=True),
        sa.Column("auto_complete_from_children", sa.Boolean(), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "estimated_duration_minutes IS NULL OR estimated_duration_minutes >= 0",
            name="ck_task_estimate",
        ),
        sa.CheckConstraint(
            "importance IS NULL OR (importance >= 1 AND importance <= 5)", name="ck_task_importance"
        ),
        sa.ForeignKeyConstraint(["entity_id"], ["entities.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["estimate_source_id"], ["sources.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["importance_source_id"], ["sources.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["parent_task_id"], ["tasks.entity_id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["primary_project_id"], ["projects.entity_id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("entity_id"),
    )
    op.create_index(op.f("ix_tasks_parent_task_id"), "tasks", ["parent_task_id"], unique=False)
    op.create_index(
        op.f("ix_tasks_primary_project_id"), "tasks", ["primary_project_id"], unique=False
    )
    op.create_index(op.f("ix_tasks_status"), "tasks", ["status"], unique=False)
    op.create_table(
        "task_dependencies",
        sa.Column("prerequisite_task_id", sa.Uuid(), nullable=False),
        sa.Column("dependent_task_id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence IS NULL OR (confidence >= 0 AND confidence <= 1)",
            name="ck_task_dependency_confidence",
        ),
        sa.CheckConstraint(
            "prerequisite_task_id <> dependent_task_id", name="ck_task_dependency_not_self"
        ),
        sa.ForeignKeyConstraint(["dependent_task_id"], ["tasks.entity_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["prerequisite_task_id"], ["tasks.entity_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("prerequisite_task_id", "dependent_task_id"),
    )
    op.create_table(
        "task_goal_links",
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("goal_id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence IS NULL OR (confidence >= 0 AND confidence <= 1)",
            name="ck_task_goal_confidence",
        ),
        sa.ForeignKeyConstraint(["goal_id"], ["goals.entity_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.entity_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("task_id", "goal_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("task_goal_links")
    op.drop_table("task_dependencies")
    op.drop_index(op.f("ix_tasks_status"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_primary_project_id"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_parent_task_id"), table_name="tasks")
    op.drop_table("tasks")
    op.drop_index(op.f("ix_success_criteria_goal_id"), table_name="success_criteria")
    op.drop_table("success_criteria")
    op.drop_table("project_goal_links")
    op.drop_index(op.f("ix_events_operation_id"), table_name="events")
    op.drop_index(op.f("ix_events_event_type"), table_name="events")
    op.drop_index(op.f("ix_events_entity_id"), table_name="events")
    op.drop_index(op.f("ix_events_created_at"), table_name="events")
    op.drop_table("events")
    op.drop_table("source_dependencies")
    op.drop_index(op.f("ix_projects_status"), table_name="projects")
    op.drop_index(op.f("ix_projects_parent_project_id"), table_name="projects")
    op.drop_table("projects")
    op.drop_table("operations")
    op.drop_index(op.f("ix_goals_status"), table_name="goals")
    op.drop_index(op.f("ix_goals_parent_goal_id"), table_name="goals")
    op.drop_table("goals")
    op.drop_index(op.f("ix_entity_relations_target_entity_id"), table_name="entity_relations")
    op.drop_index(op.f("ix_entity_relations_source_entity_id"), table_name="entity_relations")
    op.drop_index(op.f("ix_entity_relations_relation_type"), table_name="entity_relations")
    op.drop_table("entity_relations")
    op.drop_index(op.f("ix_sources_source_type"), table_name="sources")
    op.drop_table("sources")
    op.drop_index(op.f("ix_decision_alternatives_decision_id"), table_name="decision_alternatives")
    op.drop_table("decision_alternatives")
    op.drop_index(op.f("ix_messages_conversation_id"), table_name="messages")
    op.drop_table("messages")
    op.drop_index(op.f("ix_decisions_status"), table_name="decisions")
    op.drop_table("decisions")
    op.drop_index(op.f("ix_entities_entity_type"), table_name="entities")
    op.drop_table("entities")
    op.drop_table("conversations")
    # ### end Alembic commands ###
