from enum import StrEnum


class EntityType(StrEnum):
    TASK = "TASK"
    PROJECT = "PROJECT"
    GOAL = "GOAL"
    DECISION = "DECISION"


class TaskStatus(StrEnum):
    TODO = "TODO"
    IN_PROGRESS = "IN_PROGRESS"
    BLOCKED = "BLOCKED"
    WAITING = "WAITING"
    DONE = "DONE"
    CANCELLED = "CANCELLED"


class ProjectStatus(StrEnum):
    PLANNED = "PLANNED"
    ACTIVE = "ACTIVE"
    PAUSED = "PAUSED"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"
    ARCHIVED = "ARCHIVED"


class GoalStatus(StrEnum):
    ACTIVE = "ACTIVE"
    ACHIEVED = "ACHIEVED"
    PAUSED = "PAUSED"
    ABANDONED = "ABANDONED"


class DecisionStatus(StrEnum):
    ACTIVE = "ACTIVE"
    SUPERSEDED = "SUPERSEDED"
    REVOKED = "REVOKED"


class SuccessCriterionStatus(StrEnum):
    UNKNOWN = "UNKNOWN"
    IN_PROGRESS = "IN_PROGRESS"
    MET = "MET"
    NOT_MET = "NOT_MET"


class DeadlineType(StrEnum):
    SOFT = "SOFT"
    HARD = "HARD"


class RelationType(StrEnum):
    RELATED_TO = "RELATED_TO"
    AFFECTS = "AFFECTS"
    SUPPORTS = "SUPPORTS"
    CONTRADICTS = "CONTRADICTS"
    DERIVED_FROM = "DERIVED_FROM"


class TransportType(StrEnum):
    TELEGRAM = "TELEGRAM"
    INTERNAL = "INTERNAL"


class MessageAuthor(StrEnum):
    USER = "USER"
    ASSISTANT = "ASSISTANT"
    SYSTEM = "SYSTEM"
    EXTERNAL = "EXTERNAL"


class MemoryIngestionStatus(StrEnum):
    IDLE = "IDLE"
    PROCESSING = "PROCESSING"
    FAILED = "FAILED"


class MemoryGenerationStatus(StrEnum):
    BUILDING = "BUILDING"
    ACTIVE = "ACTIVE"
    SUPERSEDED = "SUPERSEDED"
    FAILED = "FAILED"


class SemanticCategory(StrEnum):
    FACT = "FACT"
    PREFERENCE = "PREFERENCE"
    CONTEXT = "CONTEXT"
    IDEA = "IDEA"
    EPISODE = "EPISODE"
    CONSTRAINT = "CONSTRAINT"
    OBSERVATION = "OBSERVATION"


class ObservationStatus(StrEnum):
    CANDIDATE = "CANDIDATE"
    ACTIVE = "ACTIVE"
    CONTESTED = "CONTESTED"
    SUPERSEDED = "SUPERSEDED"


class EvidenceStance(StrEnum):
    SUPPORTS = "SUPPORTS"
    CONTRADICTS = "CONTRADICTS"


class MemoryPageType(StrEnum):
    USER_PROFILE = "USER_PROFILE"
    COMMUNICATION_PREFERENCES = "COMMUNICATION_PREFERENCES"
    PROJECT = "PROJECT"
    TOPIC = "TOPIC"


class SourceType(StrEnum):
    USER_MESSAGE = "USER_MESSAGE"
    ASSISTANT_INFERENCE = "ASSISTANT_INFERENCE"
    SYSTEM = "SYSTEM"
    EXTERNAL = "EXTERNAL"


class ActorType(StrEnum):
    USER = "USER"
    ASSISTANT = "ASSISTANT"
    SYSTEM = "SYSTEM"


class EventType(StrEnum):
    ENTITY_CREATED = "ENTITY_CREATED"
    ENTITY_UPDATED = "ENTITY_UPDATED"
    ENTITY_SUPERSEDED = "ENTITY_SUPERSEDED"
    TASK_CREATED = "TASK_CREATED"
    TASK_UPDATED = "TASK_UPDATED"
    TASK_STATUS_CHANGED = "TASK_STATUS_CHANGED"
    TASK_COMPLETED = "TASK_COMPLETED"
    TASK_CANCELLED = "TASK_CANCELLED"
    PROJECT_CREATED = "PROJECT_CREATED"
    PROJECT_UPDATED = "PROJECT_UPDATED"
    PROJECT_STATUS_CHANGED = "PROJECT_STATUS_CHANGED"
    PROJECT_COMPLETED = "PROJECT_COMPLETED"
    PROJECT_CANCELLED = "PROJECT_CANCELLED"
    GOAL_CREATED = "GOAL_CREATED"
    GOAL_UPDATED = "GOAL_UPDATED"
    GOAL_STATUS_CHANGED = "GOAL_STATUS_CHANGED"
    GOAL_ACHIEVED = "GOAL_ACHIEVED"
    SUCCESS_CRITERION_UPDATED = "SUCCESS_CRITERION_UPDATED"
    DECISION_CREATED = "DECISION_CREATED"
    DECISION_SUPERSEDED = "DECISION_SUPERSEDED"
    DECISION_REVOKED = "DECISION_REVOKED"
    RELATION_CREATED = "RELATION_CREATED"
    RELATION_REMOVED = "RELATION_REMOVED"
    UNDO_APPLIED = "UNDO_APPLIED"
